### ISSUE TITLE
README Example Out of Date?

### ISSUE THREAD

**Issue by vicatcu** [vega/vega-lite-api#10]
The primary example in the README does not match reality. The code in the README amounts to this:

```javascript
const vl = require('vega-lite-api');
const x = vl.markBar().data('data/movies.json').encode(
  vl.x().bin('IMDB_Rating'),
  vl.y().count()
);
console.log(x.toString());
```
And the README _advertises_ that it produces the following JSON:
```javascript
{
  "mark": "bar",
  "data": {"url": "data/movies.json"},
  "encoding": {
    "x": {"bin": true, "field": "IMDB_Rating", "type": "quantitative"},
    "y": {"aggregate": "count", "type": "quantitative"}
  }
}
```
But that code _actually_ renders the following JSON:
```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "mark": {"type": "bar"},
  "data": {"url": "data/movies.json"},
  "encoding": {
    "x": {"bin": "IMDB_Rating"},
    "y": {"type": "quantitative", "aggregate": "count"}
  }
}
```
In the [Vega Editor](https://vega.github.io/editor) the _advertised_ specification renders the following chart:
![image](https://user-images.githubusercontent.com/1018382/58567026-96e8e600-81ff-11e9-9c3d-e013e6de5036.png)
But the _actual_ specification renders the following chart:
![image](https://user-images.githubusercontent.com/1018382/58567103-bf70e000-81ff-11e9-89b2-4771f48eab2f.png)
Through a bit of experimentation and guess work, I modified the README example as follows:
```javascript
const vl = require('vega-lite-api');
const x = vl.markBar().data('data/movies.json')
.encode(
  vl.x().fieldQ('IMDB_Rating').bin(true),
  vl.y().count()
);
```
Which generates the following specification:
```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "mark": {"type": "bar"},
  "data": {"url": "data/movies.json"},
  "encoding": {
    "x": {"field": "IMDB_Rating", "type": "quantitative", "bin": true},
    "y": {"type": "quantitative", "aggregate": "count"}
  }
}
```
And the following chart:
![image](https://user-images.githubusercontent.com/1018382/58567253-08c12f80-8200-11e9-9fcd-f00478f93cf5.png)

But to get there I had to be explicit in the code about using the `fieldQ` method instead of just `field` method and `bin(true)` instead of `bin(fieldName)`. Whereas the README example lead me to believe that the `bin(fieldName)` method would perform some kind of inference on the data, but as illustrated above, in fact it did not.

I think either the README should be updated with my working example, or an explanation of what pre-requisites are unstated should be added. I'd be happy to issue a PR against the README if you the maintainers are in agreement with my assessment, or can please explain what I'm missing if the README is already adequate.

**Comment by jheer** [comment]
Yes, that is a rather unfortunate typo. I've already pushed a fix. Thanks for bringing this to our attention!
