### ISSUE TITLE
Ability to customize tick format

### ISSUE THREAD

**Issue by curran** [vega/vega-lite-api#12]
It would be nice to be able to define a function that formats tick values.

Not sure this is the right place in the stack to file the issue (perhaps better as an issue in `vega-lite` or `vega`), but from the JS API is definitely where I'd love to be able to define and pass in a tick formatting function.

For example (from [Ordinal Scatter Plot](https://vizhub.com/curran/a9ec621b1c36439aa2a65e0c28462d7a)):

```js
  const xAxisTickFormat = number =>
    d3.format('.3s')(number)
      .replace('G', 'B');
```

Related:

 * Twitter thread: https://twitter.com/mbostock/status/1143595076511076352
 * Plausible workaround direction: https://stackoverflow.com/questions/53265435/customise-vega-lite-line-graph-axis-labels/53472546#53472546
 * Motivating example: https://observablehq.com/@mbostock/working-with-wikipedia-data

![image](https://user-images.githubusercontent.com/68416/60235290-dd943380-98c4-11e9-9c41-b118a2266986.png)

/cc @mbostock @domoritz 

This particular issue feels like a symptom of something greater that's missing in the Vega ecosystem - there's a formidable "Wall of abstraction" that seems impenetrable. [Setting the background color](https://github.com/vega/vega/issues/191) feels like a similar symptom. If only there were some way to add JavaScript hooks into Vega itself, maybe we could bash some holes in the wall. It would be a departure from the pure JSON spec idea, but possible worth pursuing.

What if the Vega spec object could have JS functions attached to it?

Another idea: Use the SVG renderer and do post-processing of the ticks DOM.

**Comment by curran** [comment]
The original example:

```js
vl.markBar()
  .data({values: d3.zip(names, totals)})
  .encode(
    vl.y().fieldN("0").sort(null).axis({title: null}),
    vl.x().fieldQ("1").axis({orient: "top", format: "s", title: "Total revenue (est.)"})
  )
  .width(width)
  .autosize({type: "fit-x", contains: "padding"})
  .render()
```

What I'd like to be able to do:

```js
const xAxisTickFormat = number =>
  d3.format('.3s')(number)
    .replace('G', 'B');

vl.markBar()
  .data({values: d3.zip(names, totals)})
  .encode(
    vl.y().fieldN("0").sort(null).axis({title: null}),
    vl.x().fieldQ("1").axis({orient: "top", format: xAxisTickFormat, title: "Total revenue (est.)"})
  )
  .width(width)
  .autosize({type: "fit-x", contains: "padding"})
  .render()
```

**Comment by domoritz** [comment]
Your example function is simple enough that we can support it in our expression language. An easy solution that gets us 90% to what you are asking for is to give you access to the expressions in Vega-Lite. Note that you can already use expressions in Vega. 

Vega actually allows you to use arbitrary functions in expressions but it's disabled by default because many people are using Vega in environments where arbitrary code execution is a security risk (e.g. Wikipedia). Therefore I doubt we will support passing functions anytime soon.

**Comment by curran** [comment]
Thank you @domoritz for your response.

To orient myself I read about the expression language in these pages:

 * https://vega.github.io/vega/docs/expressions/
 * https://github.com/vega/vega/tree/master/packages/vega-expression

You mention the ability to "use arbitrary functions in expressions". Does that mean that in the Vega spec there would be an expression _string_ that contains the implementation of the function, which would then be parsed and evaluated by `vega-expression`? This I can understand would be a security risk, as it's essentially exposing [eval()](https://stackoverflow.com/questions/1651118/security-risks-of-using-eval-to-execute-user-input-in-javascript). This, however, is not what I had in mind.

What I had in mind was to break from the strictly JSON-serializable format of the Vega specification, and add the ability to pass in a function for the tick formatter as part of the Vega spec JavaScript Object (making it no longer JSON-serializable). If the containing environment only allows JSON to be used as input to the spec (e.g. Wikipedia), then having the ability to pass in functions on the Vega spec object would _not_ be a security risk, as the containing environment would only accept strictly JSON from user generated content. A potential attacker would have no way of attaching a function. This approach is different from exposing `eval()`, and would only be available for developers who are already writing JS that runs on the page.

Therefore, I believe what I'm proposing would not introduce any security risks, and it would enable developers to reach through Vega's "wall of abstraction" to do custom things (meaning, things that the Vega team has not considered and added APIs for). I think it would be a huge improvement. To me the strictly JSON spec format is unnecessarily restrictive, in the case we are producing it using JavaScript.

**Comment by curran** [comment]
Related https://github.com/vega/vega/issues/608

**Comment by curran** [comment]
Proposed solution direction: https://github.com/vega/vega/pull/1853

**Comment by domoritz** [comment]
Thanks for explaining your idea more. I agree with you.

However, I wonder what you think about exposing expressions for formatting in Vega-Lite do that our specs are still serializable? When would it not be enough?

**Comment by domoritz** [comment]
Since this issue is a duplicate of vega/vega#608, let's keep the conversation going over there.

**Comment by curran** [comment]
@domoritz Exposing expressions for formatting in Vega-Lite may be able to address the immediate need, namely this part `.replace('G', 'B')`. Is there already syntax for String replacement? It may be that this is possible, and I just don't know how to go about it.

That said, what happens when someone wants a custom format that is unforeseen by the expression formatting provided? From a more philosophical point of view, I do like the idea of being able to pass functions. From a practical point of view, perhaps we could get by without doing this.

I think it does make sense to close this issue in favor of vega/vega#608, but at the same time, this issue is in the context of the JS API, where passing a custom function would make more sense than in the general case of Vega.

At the end of the day, what I'd really like to see is a working implementation that formats this original example https://observablehq.com/@mbostock/working-with-wikipedia-data using "$90B" rather than "90G".

Thanks for your input on this!

**Comment by arvind** [comment]
Hi @curran, what you're asking for is mostly possible in the Vega stack. [Here is](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQA4t27UANsgDksMLDzd4AazCFN8ZGG5V1YHamR0FJUh0VjtYRgAvZGwoQnRlQIhIOOVlRhlqGNFFJIB3RmUWLIAGYpyoWwBPcxjIN1NTRJV0PEwcAG0lCFAIXqgZdD9a6VZ1NwB9Yqa+yAp0U1Y1GM6+vvbIAAVuBwBL1FkFMABOUtOz4oBdctWwdYAJZAbuMABpZjxKw4AOc-OrrtW6wA6ukZIx3Cx3FtuIhDgB2US-U7-G4QdYAWUYjmQlTA6O4rFg7gAZGAAGKaZAyZSweFI5HXQGQADKrW8QPQ6lp8jAADZEfSUaj1gBBGRxGQYOQ83n00pCm7rAAijFgMhxYA2mhkblg3LAABYDXDBYy1pB0ZyeIcAMyy00A83MxCAWUB1TIwAApVioQhgUhen1+gDC3FQWP1NoNcoVTMt6iopjAwfSaBaWLAAFUwV4ibaAEwxs29YGRTlpDJgIHcdSmZT+sB3TnqXFbAjIdS2gCMRcdJZZhAKHYAtJbpWB8yaHajboZWNTBod8-akbHzQAhFpSpcC1fFtGQJXqdDUWRgTcNJfR6fCyCb9TscFX3sz9Zk1V4DwAMx8KDAADkaxYMBWU5JdCxvRVIGDTl9XzCC9z7A8AHl1U1cE3CXHtIKZAAVbhcVZGtPh5Qtr1+Nd+0xVJzGHZBOWAgMABka3rbgf0hMAACV0mofUuyOE5ENfSBPUGNRz1kBIeQEoSKP3WcAE1WGHAxGGHZDEAAQkOASfmE28NnomRQn4uFyL+BT1lw48ZFgL8az8LldLhBDLKQ2cYIab8wCVUISLALspwMqD-2QM8DCpNRVTAABROYMkeXRdN5G0cPNF57EQRgXnElK0pCplmVYQgOxAqlWkYBstlyMquPQRLnJk3k3LOSiDyVGt0F-dxYoAD0IUwaw7XTRGC9yRNwv9mUYX1pDs0aCvkjz1g2dB4FHBrRuw5aRJBKqiUpfiDX03bb2ZdBGCG7x8QOGSDSWibbxY2QNVw+clnu1qGRWgdZGoZB124dgQIAR1YTlkDWmQ8GOnanqg5k4jcMAAEkZDmVQmsCm05IRvC-yY3RXl43SbVO-HzRFKhGv4qN0v7XDkCpE93HRUIGs-f90gkbr3vUPBzH4ycGY649Tw9ABFRZbF0-MLLaqzIHfAYkzJTn0FgAKuwE0XZz8xKz3fah8DK1DTFTXSuwpxXfszUw8GPbcZK7FdKf7Vl1GZz9jdNzsXd3d2DwpbgonHHXHttkTitK9RncCnW9eBTl4GPL88Ct+Go9vYN1G4PV3y93Tijd7PEbZMAbOQBxi9Ln6RP-TlQm4Yus-r29PW4TurHPMt1C9sARWUGm8FGaIeSOG326ggxbPrKbkHTwfm8OI5ccKqmMhbXv1Bpb44Sny4lamsNNbAUkKXBal9S+BEN-7Jj6OoRYfMfgHr++XGp-a2dmTUcSQKO29g2BeeISqlVht8A0eNp5MiVGoQc8B0DsHMHidwAZMRglkDfO098DzemPHqDMa11A1x5F8XWZ0oIbEYMePAEl2I9WTFadg7BjLwiOG3I+v1mSyAzJxB4ygAaIBMPCfMgdYEbipIFKYPID4SPlErAAGqOKk8ID54NnFqZABBcTBjHg2AwFt2zeDJDWTCcjRCR0Ub9Tqx40B3TAK5GBNiRL4jsvQ7wntGAOHHk48Rmj1jrnMOtWEcj5aBM2KwCIERUGkiPCebBdJD4-1WiKIEmoWh50aHIl8t4gRqDwLkcsXoCTqHVAFfk31uEiSbENQ4-Ik6HmDHFPq9DqTIHrNmRguY-G8hOpE3C+QLYmwzjKdeVC4GMCYPsccqU641NvKAjYiBOZhh8pxZCsdMAyngoMwYiS8BIEYA06piyoIilMPECsDTE6TPNPA+h8AdBUGTLIBqDYYJEmTENIk0k+TFC4akyAqMUYigBg0vJUFMHIFTugdOhxRAUMic6L2ZCwBjQVq428IoQL-R8qC9wDV6yF3QRAAwADGFTTzuqfUSKgVK3VrYc+5JRg8EJIi3kDLfpcWiqoGGcUKBXURaILF5ymQwQHuuei2NEQKPFeafEAt5ivDDOwFoiKoVMiBiDTi65WBXSxpqppMFqR6PUISRAIETw7MNEcBZwLmRXNQL5ec6KTrcpEpfKke8eQDMidKyoKD4h+INAshVjM-zrmmeeBq1BK4oGIocA0Y1IkvB9IMRxKbrERoPIpbgw4HCXSrC0JAyabTjUkf2EUepNbhBkD3XOzN-kPTFcCriowCRgleFSWA2UPQBguqgUYxalHls9bedEuIiYEFQVsGQAUHpNLuPOTxYAADrjZV0jT9fmHNwL1b0OTSXQZf4V2NTABSvw+pozyuBZiIhsgcCo19PncIKDQ1aqdI7dAuQ2H90IiIgWSDfHHqabPD5-NVT7DA6uPsFwAQAF9GQ9FWJAAYQx9DKBaOgSY0xeiQBGGMaI+giMTFkX2SAP67IOTjssDyqGZxUcqKVWoX4rqePwzcSAyABqdiwy0H07QAA6kAuyiYuGALSABeaTYATLeWJKSLSqpG7-gABTYdHqgETYmJMAEpIAeUQ-BpDSghSEemarWkHQATAHQ3lfQlRxi2GQIQQ4sx5iLBiIWZDdnKMYZI7gZA0z8BcagCVLTQXIDquvsjZAmnT7pHUxYSoFh9N0HMBkFgPJih0C7LlugxRRD6bAAAKjAM51z7mzMQAsxgUhNnbj+e44F2oDWHDckox8Vj+gvbPPC4Rj4NQOgxbApRSAX486oBiPZrTbRmitDw357jVJ4DcFULNjykBIstCC4x1Ek2rqNBwPZuYCxosAGIDTwAPugL4kAVszigHYbgDstBbeewR8I1BVa1GAKJ4oomcAWAsAAai00JwHEmeSifEzEWjGA8CacEzpuHMOwCidgKJ-TiGjNfae0xvqs3CNIJG1AYnPIjuPASPoLsj2FJJD6vmEnCB5jRcp1Ac73mcDFEJ4dz4p3Sfs9qAFandZahTH59xlAoWM5C7Z+TyAYvYu058Ba5AJmZxa9WDriAOuLOK6WLZvoB2khtf0JT7rLHosW3VGBYskBlBJb0GAObOHajzbw1T9jNPaj0+l1AWyEKOhlDd5Z378xaj5EKLCRDE2wSYRwI7RYjuoh5xiCn5ASGUMBcc1AEi1vetQFV4N53GB0gk-m57nD3uoC+4l-oWRFQgKZ414HyAwf9tDbc6zqzUenMufoe5xDHeUgVmoOjdU-GwB5YK5R8fvFkKhBGrzorohatgAs+gPqxvmum8o0b2oVvuM1ivvLl73B3OO+oJoNXX55hEkdzoQW0X6eO8Rxq0jg2rlsNMGSBYPtNvVPSjX-R4ZCLwK5dzZPDXZ-LEBwUMVdPvSPE7KANwK6dTGPFgUgaMQzDvCIdIVQYnHAefVbHUDbfbbbMA0wJrM3AjXbI9U7DyJIehNpZAv7PrNzK5NwFHbTTLZBR4HkCwAwCwIQ9cdLR7ZgsAPXXXPsGQ-nOg4XJXE-NDM-CqWoOwa-SjW-AoZkMnaLQvbjHQtXLPOAxwRAmGdggfNAkLUwTAgobA3AhnSjcvS6V3B-Gg5AR3agprDwp-SjDAPqfqdpC-MoAI9IYI9Q3nMwzrBHR-LwyjAgjpYg2fHPOzJQgwjzNQyw-QcwBFKnYwuIzwqnF-JXZvSAJIogmILsA3EARDIAA) the same chart with a Vega expression function doing the string replacement in this block of code:

```json
  "axes": [
    {
      "scale": "x",
      "orient": "top",
      ...
      "encode": {
        "labels": {
        "update": {
          "text": {"signal": "replace(datum.label, 'G', 'B')"}
          }
        }
      }
    },
```

Right now, I don't think we surface the ability to modify axis/legend encodings within Vega-Lite but we can certainly consider what the best way of doing that is.

**Comment by curran** [comment]
@arvind This is amazing! Thank you for putting the time into investigating this. It's reassuring that it's possible to do this in Vega. Looking forward to ways this might be doable in Vega-Lite, and especially in the Vega-Lite JavaScript API.
