### ISSUE TITLE
Readme: Document functions like toView() and toSpec().

### ISSUE THREAD

**Issue by hastebrot** [vega/vega-lite-api#13]
Seems that `render()`, `toView()`, `toSpec()` and `toString()` are not documented in `README.md`.

~~Also I have to write `spec = vl.data().transform(...transforms)` (forced to call `data()` before `transform()`) in order to use it with `react-vega-lite` as `<VegaLite spec={spec} data={data} />`.~~

References:
- https://github.com/vega/vega-lite-api/blob/4ab26cd222557bd57743af1a72c5a21e260339ab/static/__view__.js#L39-L59
- https://github.com/vega/vega-lite-api/blob/c84ccaf984c89d5c575bca0f91186d936429e367/api/types.js#L396-L401

**Comment by domoritz** [comment]
Can you make a separate issue for the second part?

**Comment by hastebrot** [comment]
@domoritz Sure. I've created #14.

**Comment by jheer** [comment]
Thanks. The documentation needs updating, and we'll get to this!

**Comment by jheer** [comment]
The library now includes rudimentary documentation generation for all methods, pulling from the existing Vega-Lite schema where it can. See https://vega.github.io/vega-lite-api/api/
