### ISSUE TITLE
Graphic-wide summarizing

### ISSUE THREAD

**Issue by gordonje** [vega/vega-lite-api#150]
Hello, I really appreciate all of your awesome work!

If I wanted to sum one of the fields in my data (or perform some other aggregate), and then add that sum to the text of my title, how would I do that using VL's API?

Currently, I'm importing d3-arrays and using it's methods to calculate these values outside the context of my marks. Which works fine.

Related question: Is it possible to access the datalib's methods via the VL API?

Thank you again.

**Comment by domoritz** [comment]
Yes, you can add an aggregated value to a tooltip. Here is the JSON version that you could base your chart on [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICCNsRpwIUmfIC+S5NoDW+pkm2KQcWVDbKassjRQAA8gkCZ-NExtBjglADNzQWV9AEkAWQARACEAfQAlNX9ApUwATxw4fQBHBiRZTDoi0hA7EDKwpDIybT5MKvQfBgaPcsqauoamxpa2zDY2QUacNABtUC6evoGQIZHSukEdvcxWgF0bGyA).

**Comment by gordonje** [comment]
Thanks for your prompt response. While adding an aggregated value to a tooltip is really useful, I'm trying to add an aggregated value to a title (or subtitle or other annotation for that matter). In my particular case, I'm trying to sum a column's values into a single value, not multiple values per group.

Following the movies example you provided, the work-around I'm using is:

```js
movies = d3.json("https://raw.githubusercontent.com/vega/vega-lite-v1/master/data/movies.json")
sumUSGross = d3.sum(movies, d => d.US_Gross)
```

Then later:

```js
vl.markBar()
  .data(movies)
  .encode(
    vl.x(
      {"bin": true, "field": "IMDB_Rating", "type": "quantitative"}
    ),
    vl.y(
      {"aggregate": "count", "type": "quantitative"}
    ),
    vl.tooltip([{"aggregate": "count", "title": "count"}])
  )
  .title({
    "text": `Movies have grossed ${d3.format(",")(sumUSGross)} in the U.S.`
  })
  .render()
```

**Comment by domoritz** [comment]
Right now, you cannot put sums into titles. Instead of datalib (which is not used anymore) you can use dataflow API https://github.com/vega/dataflow-api.
