### ISSUE TITLE
.encode vs .encoding

### ISSUE THREAD

**Issue by john-guerra** [vega/vega-lite-api#161]
Hi!

Not sure if this is an issue or not, but after working in the vl api for a while, and having failed to generate:

~~~
{ 
   encoding : { ... },
   layer: {...}
}
~~~

I just realize that you must do 

~~~
vl
   .layer(...)
   .encoding(...)
~~~

This wasn't obvious to me because I was under the impression that in the vl-api one should use `.encode()` instead of `.encoding()`, because you use encode to define the encoding for marks.

**Is there a reason for using `.encoding` for `.layer` instead of `.encode` ?**

As context, I got into this by trying to translate the parallel coordinates example to the vl-api

https://observablehq.com/d/f41079165f8f8e8e

Also, it seems that for using `.layer()` and `.encoding()` you need to pass an object as in:

~~~
vl.layer(...)
   .encoding({ y: vl.y().value(0))
~~~

Leaving this here, in case someone else gets into this

**Comment by jheer** [comment]
Thanks for catching this! I've updated the API and test cases to ensure the proper `encode` method is exposed.

**Comment by john-guerra** [comment]
Thanks a lot Jeff!

I wish I could be of more help submitting bugfixes rather than just bugs, but I still haven't been able to wrap my head around the vega-lite-api code. Is there any resource I can explore to understand how it works for future collaborators?

**Comment by jheer** [comment]
Thanks John! I should write up a guide to VL API code at some point. The key bit to know is that it is actually multiple separable pieces: an API generator that takes an API description and corresponding JSON schema as input (in `/api/generate`), the Vega-Lite API description itself (in `api/`), and then the generated VL API code (written to `/src/` by the build process). It is understandably hard to grok, as I've written no documentation for the API description schema yet...
