### ISSUE TITLE
Missing markSymbol

### ISSUE THREAD

**Issue by seanlaff** [vega/vega-lite-api#175]
I didn't see markSymbol() in the docs, as a workaround I tried

```js
    vl.mark({
      "type": "symbol",
      "encode": {
        "enter": {
          "fill": {"value": "#939597"},
          "stroke": {"value": "#652c90"}
        },
        "update": {
          "x": {value: "openTime"},
          "y": {value: "openPrice"},
          "shape": {"value": "arrow"},
          "opacity": {"value": 1}
        }
      }
    })
```
but hit an error `TypeError: Cannot read property 'filled' of undefined`

**Comment by jheer** [comment]
It looks like you are trying to write Vega? This is the **Vega-Lite** API.

**Comment by seanlaff** [comment]
Ah, sorry I had the documentation between vega and vega-lite criss-crossed. What I wanted was this https://vega.github.io/vega-lite/docs/point.html#properties
