### ISSUE TITLE
Vega-Lite API displaying (bounding) box instead of GeoJSON feature

### ISSUE THREAD

**Issue by chrispahm** [vega/vega-lite-api#197]
First off, thanks for this wonderful piece of technology!

Today I had some trouble rendering some GeoJSON features using vega-lite: 
The following GeoJSON polygon
![image](https://user-images.githubusercontent.com/20703207/97279671-93fe8480-183b-11eb-95ee-e9b019a8f757.png)

Is displayed as a simple box using the following `vega-lite-api` code:

```js
vl
  .markGeoshape()
  .data([feature])
  .encode(
    vl
      .color()
      .fieldN('properties.D_USE')
      .legend({ title: 'Land use type' })
  )
  .config({ view: { stroke: null } })
  .render()
```
![image](https://user-images.githubusercontent.com/20703207/97279863-cf994e80-183b-11eb-89fa-b0e3ffe05103.png)

The same code already worked on a similar dataset, where the `vega-lite-api` produced the desired results. 

When looking for similar issues I found these two https://github.com/vega/vega-lite/issues/4165, https://github.com/vega/vega/issues/1405. While the first issue got closed in favour of the second, I highly suspect that they not really related as my input GeoJSON shape is both far from being rectangle shaped, as well as way too small to be affected by a reprojection distortion as described in https://github.com/vega/vega/issues/1405. 

Here is a small observable showcasing the issue:
https://observablehq.com/@chrispahm/vega-lite-api-displaying-bounding-box-instead-of-geojson-fe

Thanks a lot for having a look!
Best
Christoph

**Comment by jheer** [comment]
It looks like your GeoJSON coordinates are in the wrong winding order. This is something that [d3-geo](https://github.com/d3/d3-geo) (which Vega/Vega-Lite depends on under the hood) is sensitive to.

I added the following line to reverse the coordinate order: `feature.geometry.coordinates[0].reverse()`

The projection then showed up as intended.

Thank you for including such a nice notebook that made this easy to inspect!

**Comment by chrispahm** [comment]
Thanks so much for solving this! 
I tried the turf.js `rewind` method at one point, but forgot to pass the `reverse` flag in the options... Therefore came to the wrong conclusion that the winding wasn't the problem.

Anyway, thanks for the quick help, I also made an update to the notebook so if anyone stumbles upon they see the solution right away 🙂 
https://observablehq.com/@chrispahm/vega-lite-api-displaying-bounding-box-instead-of-geojson-fe
