### ISSUE TITLE
vega-lite-api roadmap ?

### ISSUE THREAD

**Issue by icem7-open** [vega/vega-lite-api#224]
This api is very convenient and pleasant, makes my life easier than if i had to write full json specs!

What about its next future and roadmap? I am thinking especially about animations, and more generally what is brilliantly exposed here:
https://observablehq.com/@observablehq/after-vega-lite

**Comment by domoritz** [comment]
The roadmap for the Vega project is at https://github.com/vega/roadmap.

**Comment by icem7-open** [comment]
Thanks for the link!
My question was more specifically about vega-lite-api. Maybe it is obvious for you that this api will live and flourish, will automatically follow vega evolutions.

Whatever, i love that api, without it, it would be difficult for me to use vega-lite.

**Comment by domoritz** [comment]
We plan to support vega-lite-api and make it follow Vega and Vega-Lite releases. We are committed to the point that we added vega-lite-api to the dropdowns on the Vega and Vega-Lite (coming with next release) websites. The API may not be updated immediately when we release new Vega-Lite versions, though. 

<img width="206" alt="Screen Shot 2021-01-27 at 14 33 04" src="https://user-images.githubusercontent.com/589034/105998085-22fc8200-6061-11eb-972d-00a50d9836c9.png">

**Comment by icem7-open** [comment]
Thank you for the confirmation!
