### ISSUE TITLE
Ability to re-render the graph using "data enter-exit" pattern 

### ISSUE THREAD

**Issue by rlishtaba** [vega/vega-lite-api#232]
Hi vega-lite-api authors,

The flexibility of the API is amazing, thank you. However, I am having a *hard time* figuring out **how to update the already rendered graph with new data** (with a subset, superset, or completely new data). 

What would be the correct way of creating a changest and then applying it to the current state of a graph?

**Comment by domoritz** [comment]
Vega-Lite api just generated Vega so it doesn't necessarily control how you render the chart. What you need to do is use the Vega view api to update the data in the chart. 

If you tell me what environment you are in, I can find an example.

**Comment by rlishtaba** [comment]
Thanks for the quick reply @domoritz. I'm using Ember.js. However, I am ok with any authoritative example, I should be able to continue from there.

**Comment by domoritz** [comment]
Take a look at https://vega.github.io/vega-lite/tutorials/streaming.html and let me know if you have questions.
