### ISSUE TITLE
Vega-lite-api@5 breaks vl.tooltip with multiple fields

### ISSUE THREAD

**Issue by vorbei** [vega/vega-lite-api#247]
Encodings like:

      vl.tooltip([
        { field: 'totalMortality', format: '.2f', title: 'Total Martality' },
        { field: 'zoneName', title: 'Zone' },
        { field: 'crudeDeathRate', format: '.2%', title: 'Death Rate' },
        { field: 'morbidity', format: '.1f', title: 'Morbidity' }
      ]),

No longer works in Vega-lite-api@5, works fine in Vega-lite-api@4

**Comment by jheer** [comment]
Thanks! Fixed in the `v5.0.0-beta.3` release.
