### ISSUE TITLE
use only parentheses in the API for everything, Curly braces are intimidating 

### ISSUE THREAD

**Issue by djouallah** [vega/vega-lite-api#3]
just my first reaction reading some code from Observable 
for example here 
```
const axis = {
    domain: false,
    ticks: false,
    title: false,
    grid: true,
    gridColor: '#888',
    labelAngle: 0,
    labelPadding: 8,
    labelFontWeight: 'bold'
  };
```
can we use parentheses instead 

same here
```
const lines = vl.markLine({
      strokeWidth: 1.5,
      opacity: 0.5
    })

```
and here
`const domain = ['petalLength', 'petalWidth', 'sepalLength', 'sepalWidth'];`

**Comment by jheer** [comment]
Thanks for the suggestion, but no, we can not use only parentheses. These are standard JavaScript constructs -- necessary basics for working with the fundamental data structures (objects `{}`, arrays `[]`) that the language provides. Sorry!

In case it helps, we shared (an intentionally terse!) primer on JavaScript basics here: https://observablehq.com/@uwdata/a-minimal-introduction-to-javascript-and-observable

**Comment by djouallah** [comment]
Jeffrey,  Sorry,  I misunderstood the purpose  of this Library, I thought it is a neutral language to describe graphics,  like SQL for data,  now I understand it is javascript.
Btw thanks for creating VEGA in the first place
