### ISSUE TITLE
Release a build for Vega Lite 5.2

### ISSUE THREAD

**Issue by DingoEatingFuzz** [vega/vega-lite-api#377]
I've been having a great time using these JS bindings! It's a huge DX improvement over writing JSON 😅 

However, I just reached for a `yOffset` encoding only to learn that it was [added in Vega Lite 5.2](https://github.com/vega/vega-lite/releases/tag/v5.2.0) and therefore not in vega-lite-api, which is for Vega Lite 5.0.0.

Maybe this is naive of me to think, but given that the 5.2 schema upgrade isn't a breaking change, it seems like releasing a 5.2 build would be as straightforward as bumping the Vega Lite dependency and rerunning the build script (🤞)?

Would you welcome a PR for this?

**Comment by gjoseph92** [comment]
Just ran into the exact same issue!

**Comment by bmesuere** [comment]
I had the same issue. Solved it by passing an object to the encode function like
```
    .encode(
      vl.x().fieldQ("rate").title("Identification rate"),
      vl.y().field("sample").title(null),
      {yOffset: {field: "FDR", type: "ordinal"}}
    );
```

**Comment by jheer** [comment]
I released a new version of the API based on the Vega-Lite 5.6 schema.
