### ISSUE TITLE
$schema update to v4.json

### ISSUE THREAD

**Issue by vorbei** [vega/vega-lite-api#99]
I'm using this api all the time on observableHQ, but recently I found 'labelExpr' doesn't work at all. I debugged and found the spec this API generates still uses 'https://vega.github.io/schema/vega-lite/v3.json', which doesn't include 'labelExpr' and some later settings. currently I'm using 'toJSON' and manually change $schema and send to 'vega-lite' to render.

Just curious, is this api still being updated? I really like to use it.

**Comment by jheer** [comment]
Yes, I plan to update it, when I can find the time. There is already a PR in the works but I need to update it to the latest VL version.

**Comment by jheer** [comment]
Done! Released as vega-lite-api version 0.2.0. Observable should be updated shortly.
